name: CI Pipeline Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mã nguồn từ GitHub
      uses: actions/checkout@v3

    - name: Cài đặt Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Chạy Test để kiểm tra code
      run: npm run test
